name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: [stable]

    runs-on: ${{ matrix.os }}
    env:
      GO_VERSION: ${{ matrix.go }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean --skip publish

      - name: Go build
        run: go build

      # To replace build with tests when available
      # - name: Go test
      #   run: go test -v
