name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: [stable]

    runs-on: ${{ matrix.os }}
    env:
      GO_VERSION: ${{ matrix.go }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Go build
        if: matrix.os == 'ubuntu-latest'
        run: go build -o "dist/buddy-linux-dev"

      - name: Go build
        if: matrix.os == 'macos-latest'
        run: go build -o "dist/buddy-darwin-dev"

      - name: Go build
        if: matrix.os == 'windows-latest'
        run: go build -o "dist/buddy-windows-dev.exe"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: buddy-dev
          path: dist/*
          retention-days: 1

      # To replace build with tests when available
      # - name: Go test
      #   run: go test -v
