name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: ["1.22", "1.21", "1.20"]

    runs-on: ${{ matrix.os }}
    env:
      GO_VERSION: ${{ matrix.go }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Go build
        if: matrix.os != 'windows-latest'
        run: go build -o "dist/buddy-${{split(matrix.os, '-')[0]}}-${{ matrix.go }}"

      - name: Go build for Windows
        if: matrix.os == 'windows-latest'
        run: go build -o "dist/buddy-windows-${{ matrix.go }}.exe"

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: dist/
          retention-days: 1

      # To replace build with tests when available
      # - name: Go test
      #   run: go test -v
