name: Release

on:
  release:
    types: [published]

env:
  PYTHON_VERSION: 3.11

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    steps:
      # Setup Section
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Get Tag Branch
        id: tag_branch
        run: |
          commit=$(git rev-list -n 1 ${{ github.ref }})
          branch=$(git for-each-ref --format='%(refname:short)' --contains $commit | head -n 1 | cut -d "/" -f 2-)
          echo "Origin branch for tag is $branch"
          echo "branch=$branch" >> $GITHUB_OUTPUT

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # Build Section
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1.0.2
        with:
          platforms: "linux/amd64, linux/ppc64le, darwin/amd64, darwin/arm64, windows/amd64"
          package: ""
          name: "buddy-${{ github.ref_name }}"
          compress: true
          dest: "dist"

      # Documentation Section
      - name: Install towncrier
        run: pip install towncrier

      - name: Check for full release
        id: check
        run: |
          version=${{ github.ref_name }}
          if [[ $version =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "full_release=true" >> $GITHUB_OUTPUT
          elif [[ $version =~ ^v[0-9]+\.[0-9]+\.[0-9]+-.+$ ]]; then
            echo "full_release=false" >> $GITHUB_OUTPUT
          fi

      - name: Draft Release Notes
        id: draft
        shell: bash
        run: |
          release_notes=$(towncrier build --version="${{github.ref_name}}" --draft)
          release_notes="${release_notes//'%'/'%25'}"                               # Multiline escape sequences for %
          release_notes="${release_notes//$'\n'/'%0A'}"                             # Multiline escape sequences for '\n'
          release_notes="${release_notes//$'\r'/'%0D'}"                             # Multiline escape sequences for '\r'
          echo "release_notes=$release_notes" >> $GITHUB_OUTPUT

      - name: Run towncrier
        if: ${{ steps.check.outputs.full_release == 'true' }}
        run: towncrier build --version=${{github.ref_name}} --yes

      - name: Run towncrier
        if: ${{ steps.check.outputs.full_release == 'false' }}
        run: towncrier build --version=${{github.ref_name}} --keep

      - name: Commit Changelog Changes
        run: |
          # > ~/.gitconfig
          git config --global user.email "noreply@github.com"
          git config --global user.name "GitHub Action"
          # git config --global url."https://oauth2:${{ secrets.PAT_TOKEN }}@github.com/".insteadOf "https://github.com"
          # git remote set-url origin "https://oauth2:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}"
          git checkout "${{steps.tag_branch.outputs.branch}}"

          # Commit changes
          git commit -m "Update changelog for ${{github.ref_name}}"

          # Push changes to origin branch
          git push --force

          # Force tag update
          git tag ${{github.ref_name}} -f -m "${{github.ref_name}}"

          # Push tag
          git push origin ${{github.ref_name}} --force

      - name: Update Release
        uses: svenstaro/upload-release-action@v2
        with:
          prerelease: ${{ steps.check.outputs.full_release == false }}
          release_name: Release ${{ github.ref_name }}
          body: ${{ steps.draft.outputs.release_notes }}
          tag: ${{ github.ref }}
          file: dist/*
          file_glob: true
          overwrite: true
